youwol/py-youwol

- youwol/routers/upload/router_data.py
- youwol/routers/upload/router_flux_apps.py
- youwol/routers/upload/router_packages.py
- youwol/routers/upload/utils.py
see https://www.notion.so/youwol/upload-img-description-etc-when-uploading-asset-215b159bd4a343a3b7a396b6ac508d21
> Feature/assets upload/sync metadata

- youwol/utils/utils_low_level.py
> 🐛 fix shutdown script POSIX conformance

- .github/workflows/pull_request_checks.yml
> TG-90 : combine in single artifact

- youwol_tree_db_backend/root_paths.py
- youwol_tree_db_backend/utils.py
> TG-100 get item from treedb is not restricted to priviledged group

- youwol_utils/types.py
> TG-109 py-youwol: wrong JSON type definition

- youwol/start.py
> TG-110 py-youwol shut down

- youwol_assets_backend/root_paths.py
- youwol_assets_backend/utils.py
- youwol_assets_gateway/routers/assets_backend.py
> TG-112 assets-backend => move permission checks upstream

- youwol/environment/projects_loader.py
> TG-101 : 'projects loaded/projects error' logs in py-youwol

- youwol_assets_gateway/routers/treedb_backend.py
- youwol_tree_db_backend/root_paths.py
- youwol_tree_db_backend/utils.py
> TG-111 treedb-backend => move permission checks upstream

- youwol/configuration/models_config.py
- youwol/configuration/models_config_middleware.py
- youwol/environment/configuration_handler.py
- youwol/environment/youwol_environment.py
- youwol/fastapi_app.py
> TG-117 implement custom middlewares & flow switchers

- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/package.json
- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/tsconfig.json
> TG-97 : Shared config for Typescript

- youwol/routers/environment/download_assets/common.py
- youwol/routers/environment/download_assets/data.py
- youwol/routers/environment/download_assets/flux_project.py
- youwol/routers/environment/download_assets/story.py
- youwol/routers/environment/upload_assets/flux_project.py
- youwol/routers/local_cdn/implementation.py
- youwol/routers/local_cdn/router.py
- youwol_flux_backend/__init__.py
- youwol_flux_backend/utils.py
> TG-113 fix 'download-asset'

- youwol_assets_backend/utils.py
> TG-124 : remove dead code youwol_assets_backend.utils.extract_zip_file

- youwol_flux_backend/utils.py
> TG-125 : do not use md5sum external command

- youwol/configuration/defaults.py
- youwol/configuration/models_config.py
- youwol/environment/configuration_handler.py
- youwol/environment/models.py
- youwol/environment/paths.py
- youwol/environment/youwol_environment.py
- youwol/routers/environment/router.py
- youwol/utils/utils_low_level.py
- youwol_data/config.py
- youwol_data/remotes-info.json
- youwol_utils/utils.py
> TG-61 : remove host & openIdHost duplication in Configuration

- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/package.json
> TG-153 : wrong relative 'dist' dir

- youwol_accounts/openid_rp_paths.py
> TG-156 : use user auth flow in auto login if no admin client

- .github/workflows/pull_request_checks.yml
This reverts commit a6fcab5a02e269bf9a234756c8e80025f0e09106.
> Revert "👷 temporary use feature/0.0.2 branche for todo-app-ts"

- youwol/pipelines/pipeline_typescript_weback_npm/regular/skeleton.py
- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/README.app.md
- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/README.lib.md
> TG-362 : Blank line in README.lib.md if no testConfig

- youwol/environment/models/learn_py_youwol_config.py
- youwol/environment/youwol_environment.py
- youwol/routers/environment/router.py
> TG-343 : be able to load 'predefined' config

- .github/workflows/pull_request_checks.yml
- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/package.json
> TG-382 : @youwol/eslint-config < 0.0.4 have been unpublished

- .github/workflows/check_all_oses.yml
> TG-165 : add python 3.7 to check_all_oses job

- .github/workflows/pull_request_checks.yml
This reverts commit 1ffa76d3f1767f34bf46bd144bca9162db07ff24.
> Revert "💚 temporary branches for http-clients & local-youwol-client"

- .github/workflows/pull_request_checks.yml
This reverts commit 65724f1c45deeca1a7cab6cd40788bcbe7c87d48.
> Revert "💚 todo-app-ts : use branch feature/sync-pipeline"

- .github/workflows/pull_request_checks.yml
This reverts commit 168825d3f0866ed1e4a97296e839cc9b4607a809.
> Revert "💚 use branches feature/jest-preset for integration testing"

- .github/workflows/pull_request_checks.yml
- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/package.json
> TG-439 : Jest Coverage broken for TS Applications

- .github/workflows/pull_request_checks.yml
This reverts commit 89874eea391bcc758fda1916728d94b3ee38a770.
> Revert "💚 branch todo-app-ts:bug/jest_coverage_provider_v8"

- .github/workflows/pull_request_checks.yml
- youwol/pipelines/pipeline_typescript_weback_npm/regular/skeleton.py
- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/auto-generated.ts
auto-generated.ts changed => need to be sync with todo-app-ts. 
PR for todo-app-ts is here: https://github.com/youwol/todo-app-ts/pull/8
> TG-441 : provide additional helpers in auto-generated.ts

- .github/workflows/pull_request_checks.yml
This reverts commit 166dad92fab59e3ee8040acc8790bbeaa0b073fa.
> Revert "💚 use branch todo-app-ts:feature/sync-pipeline-ts"

- .github/workflows/pull_request_checks.yml
- youwol/environment/models/models_config.py
- youwol/pipelines/pipeline_typescript_weback_npm/regular/__init__.py
- youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/README.app.md
- youwol/pipelines/pipeline_typescript_weback_npm/regular/webpack_dev_server_switch.py
PR coupled with this one:
https://github.com/youwol/todo-app-ts/pull/11
> #458 py-youwol: rewrite CdnSwitch to WebPackDevServerSwitch

- .github/workflows/pull_request_checks.yml
This reverts commit e65fe14ca9f75cf5f0f4978a7feb0e9decc4916b.
> Revert "💚 use branch todo-app-ts:feature/sync_pipeline_ts"

- youwol/fastapi_app.py
- youwol/web_socket.py
> TG-470 : py-youwol: handle multiple ws connections

- youwol_stories_backend/root_paths.py
- youwol_stories_backend/utils.py
After merge, new tests added in http-clients, see
https://github.com/youwol/http-clients/tree/feature/test-story-delete-page
> TG-474 : stories: Deleting document break all story

- youwol/environment/models/__init__.py
- youwol/routers/environment/router.py
> TG-477 : Py-YouWol: fix regression PathsBook.youwol

- youwol/routers/custom_backends.py
> TG-478 : Py-YouWol: fix custom-backends installation

- README.md
> TG-479 : Py-YouWol: fix README.md

- .github/workflows/pull_request_checks.yml
- pyproject.toml
- requirements-dev.txt
- requirements-qa.txt
- requirements.txt
> TG-516 : Add python deps auditing to CI

- youwol/environment/auto_download_thread.py
- youwol/environment/config_from_module.py
- youwol/environment/native_backends_config.py
- youwol/environment/paths.py
- youwol/environment/youwol_environment.py
- youwol/routers/environment/upload_assets/package.py
- youwol/routers/environment/upload_assets/story.py
- youwol/routers/environment/upload_assets/upload.py
- youwol/routers/local_cdn/implementation.py
- youwol/routers/local_cdn/router.py
- youwol/routers/native_backends_config.py
- youwol/routers/projects/router.py
- youwol/start.py
- youwol_cdn_backend/root_paths.py
- youwol_cdn_backend/utils.py
- youwol_utils/clients/data_api/data.py
- youwol_utils/clients/docdb/local_docdb.py
- youwol_utils/clients/utils.py
- youwol_utils/utils.py
> TG-423 py-youwol & multithreading & indexed data files

- pyproject.toml
- requirements-dev.txt
- requirements-docker.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- youwol_assets_gateway/routers/stories_backend.py
- youwol_utils/middlewares/authentication.py
> TG-529 : ⬆️ upgrade fastapi => 0.92.0 & starlette => 0.25.0

- .github/workflows/pull_request_checks.yml
This reverts commit ce69bc51350de7bbad7faf77c26535cbc3175ec7.
> Revert "💚 branch todo-app-ts:ci/continuous_amelioration"

- youwol/environment/clients.py
- youwol/middlewares/local_cloud_hybridizers/workspace_explorer_rules.py
- youwol/pipelines/publish_cdn.py
- youwol/routers/commons.py
- youwol/routers/environment/download_assets/common.py
- youwol/routers/environment/upload_assets/custom_asset.py
- youwol/routers/environment/upload_assets/data.py
- youwol/routers/environment/upload_assets/flux_project.py
- youwol/routers/environment/upload_assets/package.py
- youwol/routers/environment/upload_assets/story.py
- youwol/routers/environment/upload_assets/upload.py
- youwol/routers/local_cdn/implementation.py
- youwol_utils/context.py
- youwol_utils/middlewares/root_middleware.py
Add feature for https://github.com/youwol/local-youwol-client/tree/feature/test-stability
+ cleaning
> TG-435 : Unstable @youwol/local-youwol-client integrations tests

- youwol/routers/local_cdn/implementation.py
- youwol_utils/middlewares/authentication.py
> TG-530 : refactor context / request interaction

- youwol/environment/auto_download_thread.py
> TG-537 download thread stuck

- youwol/routers/projects/router.py
> TG-1049 Step execution, time-out & extra retry

- youwol/routers/native_backends_config.py
- youwol_accounts/configuration.py
- youwol_accounts/openid_rp_paths.py
> 🐛 Disable Secure cookies in py-youwol

- youwol_tree_db_backend/root_paths.py
> TG-1103 pylint E0102 : function already defined

- src/youwol/backends/cdn/root_paths.py
Issue will be closed when PR merged on the branch https://github.com/youwol/local-youwol-client/tree/feature/add-regression-test
> TG-1203 cdn-backend: version resolution if other majors already downloaded

- pyproject.toml
> 🐛 Add pipeline ts views artefacts

- pyproject.toml
- src/youwol/app/main.py
- src/youwol/app/wrapper.py
> ✨ Update PATH with sys.prefix if necessary

- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/pipeline.py
TG-1209 #closed
See example of usage in `yw_pipeline.py` here: https://github.com/youwol/cdn-client/tree/feature/2.0.5-wip
> TG-1209 be able to override steps in pipeline TS

- src/youwol/utils/clients/oidc/service_account_client.py
- src/youwol/utils/clients/oidc/users_management.py
> 🐛 [users_mgmt] no parse response on actions mail

- src/youwol/app/environment/paths.py
- src/youwol/app/environment/python_dynamic_loader.py
> 🐛 Use path relative to cwd for nonexistent config

- integrations/.gitignore
- pyproject.toml
- requirements-dev.txt
- requirements-docker.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/utils.py
> Bug/pyparsing 3.0.11

- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/skeleton.py
> TG-1289 project/lib template creation: control for valid project name

- src/youwol/app/routers/commons.py
- src/youwol/app/routers/environment/upload_assets/upload.py
- src/youwol/pipelines/publish_cdn.py
- src/youwol/utils/context.py
> TG-1381 pipeline TS & publish remote

- src/youwol/backends/assets_gateway/deployment.py
- src/youwol/backends/common/clients.py
> 🚚 Remove backends suffix -backend

- src/youwol/utils/context.py
TG-1480 #closed
This is a hotfix, see TG-1481
> TG-1480 Publication on remote env not working

- src/youwol/utils/context.py
> TG-1485 Publication on remote env (still) not working

- src/youwol/app/environment/paths.py
> --config <new_config.py> --init

- src/youwol/app/environment/models/predefined_configs/default_config.py
- src/youwol/app/environment/paths.py
> TG-1292 Use a separate resource for creating default config

- requirements-dev.txt
- requirements-publish.txt
- requirements.txt
> ⬆️ Requests-toolbelt 0.10.1 => 1.0.0

- .github/workflows/pull_request_checks.yml
> TG-1617 realization

- .github/workflows/pull_request_checks.yml
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/npm_dependencies_version.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/skeleton.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/README.app.md
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/README.lib.md
- 🐛 Pipeline TS : handle empty templating values
- ⬆️ TS shared config 1.0.0
- 💚 Temporary use feature/ts-shared-conf-1.0.0
> TS-1653 Upgrade shared configuration for TS 5.2.3

- src/youwol/backends/assets_gateway/routers/cdn_backend.py
- src/youwol/backends/cdn/root_paths.py
- src/youwol/utils/clients/cdn/cdn.py
> TG-1655 be able to retrieve package versions from semver query

- src/youwol/utils/clients/oidc/tokens_manager.py
> TG-1659 [OIDC] coroutine not awaited

- src/youwol/backends/assets_gateway/routers/cdn_backend.py
- src/youwol/utils/clients/cdn/cdn.py
> TG-1663 wrong headers on GET entry point in cdn

- src/youwol/app/fastapi_app.py
- src/youwol/app/middlewares/local_cloud_hybridizers/download_rules.py
> TG-1652 implement local/cloud middleware 'UpdateApplication'

- src/youwol/app/middlewares/local_cloud_hybridizers/download_rules.py
> TG-1665 corountine `UpdateApplication.download_needed` not awaited

- src/youwol/app/routers/router_remote.py
> TG-1669 redirect api in remote do not fwd incoming headers

- src/youwol/app/middlewares/local_cloud_hybridizers/download_rules.py
- src/youwol/backends/assets_gateway/routers/cdn_backend.py
- src/youwol/utils/clients/cdn/cdn.py
> TG-1670 UpdateApplication in py-youwol with dev-server running

- src/youwol/backends/cdn/root_paths.py
> TG-1673 cdn: can not use max_result above 1000

- .github/workflows/check_all_oses.yml
- .github/workflows/pull_request_checks.yml
- .github/workflows/release.yml
- 👷 Renaming `cdn-client` => `webpm-client`
TG-172 #closed
> TG-1712 Update CI to replace @youwol/cdn-client

- .github/workflows/docker-image.yml
- 👷 New `Docker Image` workflow
> TG-1687: Build py-youwol docker imgae for each release

- src/youwol/app/environment/youwol_environment.py
- src/youwol/app/routers/environment/router.py
- ♻️ `YouwolEnvironment` => `safe_load` can forward `token_storage`
- 🐛 [routers.environment] => forward `token_storage`
TG-1740 #closed
> TG-1740 reloading config. forget tokens

- .github/workflows/release.yml
- src/youwol/utils/crypto/file_encryption/siv_256.py
- 🐛 `release.yaml`: single '=' for posix shell
- 🚨 `file_encryption.siv256`: get ValueError msg
TG-1760 #closed
> TG-1760: Job Release: shell operator '==' not posix

- .github/workflows/pull_request_checks.yml
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/npm_dependencies_version.py
> TG-1763 Fix versions of typescript dependencies

- src/youwol/pipelines/pipeline_typescript_weback_npm/common/models.py
> TG-1662 Templating : optional values

- src/youwol/app/routers/projects/models_project.py
- src/youwol/pipelines/pipeline_raw_app/__init__.py
- src/youwol/pipelines/pipeline_raw_app/pipeline.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/utils.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/external/pipeline.py
- src/youwol/pipelines/publish_cdn.py
> TG-1852 implement pipeline_any_app

- integrations/yw_config.py
- src/youwol/app/middlewares/local_cloud_hybridizers/loading_graph_rules.py
- src/youwol/backends/cdn/loading_graph_implementation.py
- src/youwol/backends/cdn/root_paths.py
- src/youwol/utils/http_clients/cdn_backend/models.py
- src/youwol/utils/http_clients/cdn_backend/utils.py
> TG-1854 update cdn-backend endpoint + update LoadingGraph middleware

- src/youwol/app/environment/youwol_environment.py
*  📝 py-youwol invite: add `dev-portal` URL 
TG-1871 #closed
> TG-1871 Add dev-portal URL in py-youwol invite

- src/youwol/app/environment/python_dynamic_loader.py
- src/youwol/app/routers/projects/models.py
- src/youwol/app/routers/projects/projects_loader.py
- src/youwol/app/routers/projects/router.py
- src/youwol/utils/clients/utils.py
*  🔊 [utils] => `log_error` formatting improved
* 🥅 [app.environment] => improve `get_object_from_module` w/ errors
* ♻️ [app.projects] => improve `ProjectLoader` w/ errors
TG-1878 #closed
> TG-1878 manage project loading errors

- src/youwol/app/environment/youwol_environment.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/views/consistency.view.js
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/views/dependencies.view.js
> TG-1862: pipeline TS: step views should be refactored

- src/youwol/app/routers/projects/projects_loader.py
Those correspond to pipeline correctly imported, but failing to be instantiated.
> 🥅 [app.projects.`get_project`] => handle additional errors

- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/src.app/tests/fake.test.ts
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/templates/src.lib/tests/fake.test.ts
*  🚨 [pipeline TS] => fix formatting issues of `fake.test.ts`
TG-1706 #closed
> TG-1706 Invalid formatting for template src.[app,lib]/tests/fake.test.ts

- integrations/yw_config.py
- src/youwol/app/fastapi_app.py
- src/youwol/app/middlewares/local_cloud_hybridizers/deprecated_rules.py
- src/youwol/app/middlewares/local_cloud_hybridizers/download_rules.py
- src/youwol/app/middlewares/local_cloud_hybridizers/forward_only_rules.py
- src/youwol/app/middlewares/local_cloud_hybridizers/loading_graph_rules.py
- src/youwol/app/middlewares/local_cloud_hybridizers/workspace_explorer_rules.py
- src/youwol/app/routers/environment/download_assets/common.py
- src/youwol/app/routers/local_cdn/router.py
- src/youwol/app/routers/projects/router.py
- src/youwol/app/routers/system/router.py
- src/youwol/backends/assets_gateway/routers/files_backend.py
- src/youwol/backends/tree_db/root_paths.py
- src/youwol/pipelines/publish_cdn.py
- src/youwol/utils/context.py
- src/youwol/utils/exceptions.py
- src/youwol/utils/middlewares/root_middleware.py
- src/youwol/utils/utils.py
*  ♻️ [pipelines.publish_cdn] => improve readability
*  🔥 remove concept of `muted_http_errors`
*  🔊 [utils] => log when triggering `youwol_exception_handler`
*  🐛 [app.routers.system.query_logs] => fix response model
*  🚨 apply `black` formatting
*  🐛 [utils] => fix `ScopedContext.__aexit__` return
*  ✨ [utils] => `Context` provides API for futures
*  ✨ [app.routers.system.logs] => expose `future` & `status`
*  🔊 [app.routers.projects] => log `run_step` with `ctx.future`
*  🔊 [utils.root_middleware] => log `202` response with `ctx.future`
*  ✨ [app] => add handler for `unexpected_exception`
*  🐛 [utils] => `Context.future` should not await the future.
*  🚨 apply `black` formatting
*  🐛 [integrations] => update configuration w/ new API
TG-1735 #closed
> TG-1735 False error in py-youwol terminal

- .github/workflows/pull_request_checks.yml
This reverts commit 93bc696128876b69c4905c1b936f95dabc91e4be.
#1912 closed
> Revert "💚 Temporary use branches for integration"

- pyproject.toml
- src/youwol/app/routers/system/documentation.py
- src/youwol/app/routers/system/documentation_models.py
- src/youwol/app/routers/system/router.py
➕ add `griffe` dependency
✨ [app.routers.system] => add `documentation` end point
TG-1923 #closed
> TG-1923 add end-point in py-youwol to fetch module documentation

- src/youwol/app/routers/system/documentation.py
- src/youwol/app/routers/system/router.py
🥅 [app.routers.system] => hardening doc. generation
TG-1952 #closed
> TG-1952 py-youwol doc: robustify

- .github/workflows/pull_request_checks.yml
This reverts commit 98a18e1d98f24875bcadc13932de84fa20215514.
TG-1954 #closed
> Revert "💚 Use branches `feature/typescript-5.3.3`"

- .github/workflows/pull_request_checks.yml
> Revert "💚 Temporary use integration branches"

- CHANGELOG.md
- doc/assets/CHANGELOG.md
- 📝 Update `CHANGELOG.md` for `v0.1.7rc0`
- 🚨 `yarn prettier --tab-width=4 ../CHANGELOG.md`
- 👽️ Synchronize autogenerated artefacts
TG-1989 #closed
> TG-1989 `CHANGELOG.md` for `v0.1.7rc0`

- pyproject.toml
No change bring in by this pull request, only merge back tags [`v0.1.6rc0`](https://github.com/youwol/py-youwol/tree/v0.1.6) and [`v0.1.6`](https://github.com/youwol/py-youwol/tree/v0.1.6rc0) into [`main`](https://github.com/youwol/py-youwol/tree/main)
> merge back `v0.1.6`

- pyproject.toml
- src/youwol/backends/tree_db/root_paths.py
- 🚨 Add passing `mypy` checks
- 🚨 Fix `mypy` check `warn_redundant_casts`
> Setup stricter `mypy`

- src/youwol/app/routers/system/documentation.py
🥅 [app.system.doc] => robustify `get_classes_inheriting_from`
TG-1981 #closed
> TG-1981 Systematic failures on nigthly build

- .github/workflows/release.yml
- CHANGELOG.md
- 👷 `release.yml` check pipeline TS & app `./doc/`
TG-2059 #closed
> TG-2059: `release.yml` check pipeline TS & app `./doc/`

- .github/workflows/branch_release.yml
- CHANGELOG.md
- 🐛 step `create_pr` use `create_branch` output
TG-2046 #closed
> TG-2046: step `create_pr` use `create_branch` output

- .github/workflows/pull_request_checks.yml
- CHANGELOG.md
- doc/package.json
- doc/yarn.lock
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/utils.py
- 🐛 Remove `@types/node` pinned to `18.19.8`
- 💚 Use todo-app-ts#bug/ts-node-20-for-apps
TG-1983
> TG-1983: remove `@types/node` pinning to `18.19.8`

- .github/workflows/pull_request_checks.yml
This reverts commit 22eb88dadf2a160d8c198e6ad9d9f1f75f2f0f47.
TG-1983 #closed
> Revert "💚 Use todo-app-ts#bug/ts-node-20-for-apps"

- .github/workflows/pull_request_checks.yml
- CHANGELOG.md
- Merge release candidates `CHANGELOG.md`
- 💚 Fix `todo-app-ts` to working revision
> 📝 Merge release candidates `CHANGELOG.md`

- .github/workflows/pull_request_checks.yml
- .github/workflows/release.yml
- CHANGELOG.md
- 📝 Merge release candidates `CHANGELOG.md`
- 💚 Fix `todo-app-ts` to working revision
> 📝 Merge release candidates CHANGELOG.md

- CHANGELOG.md
- deps_manager.sh
- doc/src/app/py-doc/index.ts
- pyproject.toml
- requirements-docker.txt
- requirements-no-hashes.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- src/youwol/app/environment/proxied_backends.py
- src/youwol/app/environment/youwol_environment.py
- src/youwol/app/fastapi_app.py
- src/youwol/app/routers/backends/__init__.py
- src/youwol/app/routers/backends/router.py
- src/youwol/backends/cdn/utils.py
- src/youwol/pipelines/pipeline_python_backend/__init__.py
- src/youwol/pipelines/pipeline_python_backend/pipeline.py
- src/youwol/pipelines/pipeline_python_backend/template.py
- src/youwol/pipelines/pipeline_python_backend/template/pyproject.toml.txt
- src/youwol/pipelines/pipeline_python_backend/template/src/fastapi_app.py.txt
- src/youwol/pipelines/pipeline_python_backend/views/run.view.js
- src/youwol/utils/utils_requests.py
- src/youwol/utils/utils_shell.py
*  ✨ [app.routers.backend] => implement `proxied backends`
*  ✨ [pipeline-py-backend] => adapt for auto-dispatch
*  🐛 [utils] => `redirect_request` forward cookies
*  ♻️ [utils] => `execute_shell_cmd` provides on_executed CB
* 🚨 `pep8` & `black` formatting corrections
* 📝 [doc-app] => add external types URL
* ⬆️ `python-multipart` 0.0.5 => 0.0.9
* 🔨 `deps_manager.sh` => sync. documentation
* 📝 update `CHANGELOG.md`
TG-2051 #closed
TG-2072 #closed
TG-2073 #closed
> TG-2051 implement `py-backend` auto-dispatch

- .github/workflows/pull_request_checks.yml
- CHANGELOG.md
- src/youwol/app/routers/local_cdn/implementation.py
- src/youwol/app/routers/local_cdn/models.py
- src/youwol/app/routers/local_cdn/router.py
- src/youwol/backends/cdn/loading_graph_implementation.py
- src/youwol/backends/cdn/root_paths.py
- src/youwol/backends/cdn/utils.py
- src/youwol/backends/cdn/utils_indexing.py
- src/youwol/utils/http_clients/cdn_backend/models.py
- src/youwol/utils/http_clients/cdn_backend/utils.py
*  ♻️ [cdn] => package's `type` in `js/wasm`, `backend`
*  💚 Use branche `webpm-client:feature/sync-lib-type`
TG-2080 #closed
> TG-2080 CDN package's type either 'js/wasm' or 'backend'

- CHANGELOG.md
- src/youwol/app/routers/backends/implementation.py
- src/youwol/app/routers/backends/router.py
- src/youwol/app/routers/environment/router.py
- src/youwol/app/routers/system/router.py
- src/youwol/pipelines/pipeline_python_backend/pipeline.py
- src/youwol/utils/context/models.py
- src/youwol/utils/utils_requests.py
*  ✨ [app.routers.env] => `status` expose `proxiedBackends`
*  ✨ [app.routers.system] => add `query_backend_logs` EP
*  ✨ [app.routers.backends] => handle backend automatic install
TG-2085 #closed
> TG-2085 backend automatic install from local DB

- .github/workflows/pull_request_checks.yml
- Revert "💚 Temporary use branches `fix_pylint_invalid-name`"
TG-2032 #closed
> TG-2032 revert using branches `fix_pylint_invalid-name`

- .github/workflows/pull_request_checks.yml
- Revert "💚 Use branches `feature/shared_config-1.2.1`"
TG-1998 #closed
TG-1997 #closed
TG-2070 #closed
> Revert "💚 Use branches `feature/shared_config-1.2.1`"

- CHANGELOG.md
- src/youwol/app/routers/system/documentation.py
- src/youwol/app/routers/system/documentation_models.py
- src/youwol/app/routers/system/router.py
*  ✨ [system] => documentation cross-links tolerant
*  ✨ [system] => add `/documentation-check` end point
TG-2128 #closed
TG-2129 #closed
> TG-2127 improve cross-refs management in inlined doc

- CHANGELOG.md
- src/youwol/app/environment/models/defaults.py
- src/youwol/app/environment/models/flow_switches.py
- src/youwol/app/environment/models/model_remote.py
- src/youwol/app/environment/models/models_config.py
- src/youwol/app/environment/models/models_project.py
- src/youwol/app/environment/models/models_token_storage.py
- src/youwol/app/routers/system/documentation.py
- src/youwol/app/routers/system/documentation_models.py
- src/youwol/app/routers/system/router.py
*  ✨ [app.system.doc] => response include files description
*  📝 [app.env.models] => add files' doc in docstring
TG-2143 #closed
> TG-2143 Expose files in `GET:documentation`

- images/backends/Dockerfile
- images/webpm/Dockerfile
- src/youwol/backends/accounts/deployment.py
- src/youwol/backends/assets/deployment.py
- src/youwol/backends/assets_gateway/deployment.py
- src/youwol/backends/cdn/deployment.py
- src/youwol/backends/cdn_apps_server/deployment.py
- src/youwol/backends/cdn_sessions_storage/deployment.py
- src/youwol/backends/common/backend_deployment.py
- src/youwol/backends/files/deployment.py
- src/youwol/backends/flux/deployment.py
- src/youwol/backends/stories/deployment.py
- src/youwol/backends/tree_db/deployment.py
- src/youwol/backends/webpm/app/paths/common.py
- src/youwol/backends/webpm/deployment/configuration.py
- src/youwol/backends/webpm/deployment/deployment.py
- src/youwol/utils/utils.py
- 🐛 [backends] get version from yw_version()
- 🐛 [webpm] correctly report missing `key` env
TG-2068 #closed
> TG-2068 Correct version in backends header

- src/youwol/app/environment/youwol_environment.py
- src/youwol/app/routers/environment/models.py
- src/youwol/app/routers/environment/router.py
*  🥅 [app.env] => reload can not change serving HTTP port
*  ✨ [app.routers.env] => add POST `/configurations/switch`
TG-2181 #close
> TG-2181 Load config from URL in py-youwol

- CHANGELOG.md
- src/youwol/app/routers/local_cdn/implementation.py
- src/youwol/app/routers/local_cdn/router.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/external/templates/src/tests/install.test.ts
*  ✏️ [pipeline TS] => fix typo on template file
*  🚚 [routers.local_cdn] => move `emit_local_cdn_status`
*  🐛 [routers.local_cdn] => add missing `emit_local_cdn_status`
TG-2187 #closed
> TG-2187 emit 'CdnStatus' when components are downloaded

- CHANGELOG.md
- doc/front-app/yarn.lock
- src/youwol/app/fastapi_app.py
*  📝 [fastapi_app] => update `setup_http_routers` documentation
*  🐛 [fastapi_app] => fix browser caching issue w/ root EP
*  📌 [doc-app] => regenerate `yarn.lock`
TG-2224 #closed
> TG-2224 root GET end-points (e.g. '/doc', '/co-lab') are cached

- .github/workflows/pull_request_checks.yml
This reverts commit 829bfdda2aca4d80b9d52473a717d049fa66f6ce.
> Revert "💚 Temporary skip `version_monotony`"

- CHANGELOG.md
- doc/front-app/yarn.lock
- src/youwol/app/fastapi_app.py
- src/youwol/app/middlewares/browser_caching_middleware.py
- src/youwol/app/routers/python/__init__.py
- src/youwol/app/routers/python/router.py
- src/youwol/backends/cdn/utils.py
- src/youwol/utils/http_clients/cdn_backend/models.py
- src/youwol/utils/http_clients/cdn_backend/utils.py
*  ✨ [app] intercept & persist pyodide resources in CDN
*  📌 [yw-doc-app]: regenerate `yarn.lock`
TG-2238 #closed
> TG-2238 intercept & persist pyodide resources in CDN

- CHANGELOG.md
- doc/front-app/yarn.lock
- src/youwol/backends/accounts/openid_rp/paths.py
- src/youwol/utils/clients/oidc/tokens_manager.py
- 🐛 [accounts] await tokens.is_temp() while login.
- ⬆️ [doc/front-app] `express` 4.19.1 => 4.19.2
TG-2246 #closed
> TG-2246 Coroutine was not awaited

- CHANGELOG.md
- src/youwol/app/fastapi_app.py
- src/youwol/app/middlewares/local_cloud_hybridizers/custom_backends.py
- src/youwol/app/middlewares/local_cloud_hybridizers/download_rules.py
- src/youwol/app/routers/backends/implementation.py
- src/youwol/app/routers/environment/download_assets/auto_download_thread.py
- src/youwol/app/routers/environment/download_assets/models.py
- src/youwol/app/start.py
*  ♻️ [app] : simplify `AssetDownloadThread`
*  ♻️ [app] : gathers startup/shutdown actions at one place
TG-2251 #closed
> TG-2251 can not run youwol in debug

- src/youwol/app/middlewares/local_cloud_hybridizers/download_rules.py
*  🐛 [app] set no-cache for downloaded components.
> 🐛 [app] set `no-cache` for downloaded components.

- CHANGELOG.md
- src/youwol/app/environment/browser_cache_store.py
*  🐛 [app] `BrowserCacheStore`: don't serve modified files
TG-2273 #closed
> TG-2273 `BrowserCacheStore` should not serve modified files

- .github/workflows/pull_request_checks.yml
- CHANGELOG.md
- src/youwol/app/routers/system/models.py
- src/youwol/pipelines/pipeline_python_backend/template/src/fastapi_app.py.txt
- src/youwol/utils/context/context.py
- src/youwol/utils/utils_requests.py
*  ✨ [utils.Context] => expose `attributes` when creating logs
*  🐛 [app.backends] => `client.stream` do not miss data
*  💚 Use branch `feature/sync-backend-api`
TG-2284 #closed
> TG-2284 `backend.channel$` eventually miss first event

- .github/workflows/pull_request_checks.yml
*   ⏪️ Revert "Use branch `feature/sync-backend-api`"
> ⏪️ Revert "Use branch `feature/sync-backend-api`"

- CHANGELOG.md
- src/youwol/app/fastapi_app.py
*  [app] Allow missing token on `/co-lab`
TG-2286 #closed
> TG-2286 allow `on_missing_token` on `/co-lab`

- CHANGELOG.md
- src/youwol/app/routers/system/models.py
*  🐛 [app.system.backend] => fix error in backend's client
TG-2297 #closed
> 🐛 [app.system.backend] => fix error in backend's client

- CHANGELOG.md
- requirements-docker.txt
- requirements-no-hashes.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- 📌 `idna==3.7`
TG-2300 #closed
> TG-2300: GHSA-jjg7-2v4v-x38h

- CHANGELOG.md
- 📝 Prepare `CHANGELOG.md` for final release
> Prepare `CHANGELOG.md` for final release

- CHANGELOG.md
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/utils.py
- src/youwol/utils/utils.py
✨ [app.pipeline-ts] => `package.json` generation more flexible
TG-2311 #closed
TG-2312 #closed
TG-1260 #done
TG-539 #done
> TG-1260 TG-539 : `package.json` generation more flexible

- .github/workflows/pull_request_checks.yml
*  ⏪️ revert '💚 local-youwol-client use feature/improve-perf-logs'
> ⏪️ revert '💚 local-youwol-client use feature/improve-perf-logs

- CHANGELOG.md
- requirements-docker.txt
- requirements-no-hashes.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- 📌 `tqdm==4.66.4`
TG-2333 #closed
> TG-2333: upgrade `tqdm` to 4.66.4

- CHANGELOG.md
- requirements-no-hashes.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
GHSA-9wx4-h78v-vm56
TG-2337 #closed
> 🔒️ Resolved security issue in `requests` dependency

- .github/workflows/pull_request_checks.yml
This reverts commit 927a5b1504821e245068014884cb1d8708a408dd.
> ⏪️ Revert "💚 use branch `feature/sync-pipeline-ts`"

- CHANGELOG.md
- 📝 [CHANGELOG.md] Missing & misplaced changes
- 🚨 [CHANGELOG.md] Format with `prettier`
- 📝 [CHANGELOG.md] Up to date help for formatting
> TG-2344: Correct `CHANGELOG.md`

- .github/workflows/pull_request_checks.yml
- CHANGELOG.md
- src/youwol/app/routers/python/router.py
*  🔊 [app.python] Add logs
* 🐛 [app.python] Robustify `get_and_persist_resource`
*  💚 local-yw-client => `use branch feature/robustify-tests`
TG-2351 #closed
> TG-2351 Brittle pyodide GET resource

- .github/workflows/pull_request_checks.yml
*  Revert "💚 local-yw-client => use branch feature/robustify-tests"
This reverts commit 1d1bd995ccd02351c333a8c2b1d7b04d8e893b42.
> Revert "💚 `local-yw-client` => use branch `feature/robustify-tests`"

- CHANGELOG.md
- 📝 Prepare `CHANGELOG.md` for final release
> TG-2347: Prepare `CHANGELOG.md` for release v0.1.10

- CHANGELOG.md
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/utils.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/external/skeleton.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/dependencies_step.py
- src/youwol/utils/utils_paths.py
*  🎨 [utils] `write_json` includes ending new-line
*  ♻️ [pipeline-ts] Enhance reliability of `DependenciesStep`
TG-2366 #closed
TG-2326 #done
> TG-2326 pipeline TS: sync dependencies

- CHANGELOG.md
- doc/front-app/yarn.lock
- requirements-docker.txt
- requirements-no-hashes.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- src/youwol/app/routers/python/router.py
- src/youwol/backends/cdn/root_paths.py
- src/youwol/backends/cdn/utils.py
- src/youwol/pipelines/publish_cdn.py
- src/youwol/utils/http_clients/cdn_backend/utils.py
- src/youwol/utils/utils_paths.py
*  ♻️ [app/CDN] Rework CDN packaging for enhanced flexibility and efficiecny
* 🔒️ upgrade `urllib3` to `2.2.2`
*  ⬆️ [doc-app] upgrade `yarn.lock`
> TG-2353 Improve package upload/download w/ brotli compression

- src/youwol/utils/clients/oidc/users_management.py
♻️ [oidc/users_management] generalize get_users
> ♻️ minor refactor

- CHANGELOG.md
- 📝 Prepare `CHANGELOG.md` for release
> TG-2392: Prepare `CHANGELOG.md` for release `v0.1.11`

- .github/workflows/pull_request_checks.yml
This reverts commit 1f6c0eb3466003fa4831a09c761dd801f7c04311.
> Revert "💚 `webpm-client` => use branch `feature/backends-with-config`"

- CHANGELOG.md
- deps_manager.sh
- requirements-docker.txt
- requirements-no-hashes.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- ⬆️ `requests==2.32.3`
- ⬆️ `pip=24.1.2`
- ⬆️ `certifi==2024.7.4`
- ⬆️ `zipp==3.19.2`
- 🔨 [dep-manager.sh] add arg `--skip-extras`
- ⬆️ `pip-tools==7.4.1`
- 🎨 [CHANGELOG.md] correct white spaces
TG-2420 #closed
TG-2419 #closed
TG-2418 #closed
> Fix GHSA-248v-346w-9cwc and GHSA-jfmj-5v4g-7637

- requirements-docker.txt
- requirements-no-hashes.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- ⬆️ `setuptools==70.3.0`
TG-2422 #closed
> Fix GHSA-cx63-2mw6-8hw5

- .github/workflows/pull_request_checks.yml
This reverts commit 6fa0a6d3d5914631cbd313d077f3d9e063ec9242.
> Revert "💚 `local-yw-client` => use branch `feature/move-out-doc`"

- .github/workflows/pull_request_checks.yml
- pyproject.toml
- requirements-docker.txt
- requirements-no-hashes.txt
- requirements-publish.txt
- requirements-qa.txt
- requirements.txt
- src/youwol/pipelines/pipeline_python_backend/template/pyproject.toml.txt
- 📌 `pip==24.2`
- 📌 `aiohttp<3.10.0`
- 💚 `webpm-client` => use `bug/demo-yw-backend-aiohttp`
- 📌 [pipeline-py-backend] `aiohttp<3.10.0`
- 💚 `local-yw-client` => `use bug/demo-yw-backend-aiohttp`
TG-2439 #closed
> TG-2439: pin `aiohttp<3.10.0`

- pyproject.toml
- src/youwol/utils/clients/assets_gateway/assets_gateway.py
- src/youwol/utils/clients/docdb/docdb.py
- src/youwol/utils/clients/storage/storage.py
* 🔥 [yw-utils] Remove unused `aiohttp.TCPConnector`
* 🚨 [yw-utils] Fix `mypy` error
TG-2438 #closed
> TG-2438 Breaking change in aiohttp>=3.10.0

- .github/workflows/release.yml
- CHANGELOG.md
- 💚 [release] allow installing local release in venv
TG-2461 #closed
> TG-2461: install local release in CI

- .github/workflows/release.yml
- 💚 [release] push versions bump after publishing
- 🎨 Cleaning `.github/workflows/release.yml`
TG-2462 #closed
> TG-2462: push versions bump after publishing

- CHANGELOG.md
- 📝 Prepare `CHANGELOG.md` for final release
> TG-2452: prepare `CHANGELOG.md` for final release

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- 👽️ [workflows] hidden files in uploaded config
TG-2464 #closed
> TG-2464: breaking change from `actions/upload-artefact`

- .github/workflows/release.yml
- 💚 [release] Checkout with depth=3 for publishing
TG-2467 #closed
> TG-2467: [release] Checkout with depth=3 for publishing

- .github/workflows/pull_request_checks.yml
This reverts commit d46718ef200edc7366709da42a5b112f9ef1437b.
> Revert "💚 `local-yw-client` => use `feature/sync-test-py-backend`"

- CHANGELOG.md
- src/youwol/pipelines/pipeline_python_backend/pipeline.py
- src/youwol/utils/utils.py
- ✨ [yw_repo_path] first try env `PY_YOUWOL_SOURCES`
- 🎨 Format `CHANGELOG.md`
- 🚨 `pyupgrade --py310-plus`
TG-2493 #closed
> TG-2493: `yw_repo_path()` in CI

- .github/workflows/nightly.yml
- CHANGELOG.md
- 💚 [nightly] py-youwol sources for tests
TG-2496 #closed
> TG-2496: Nightly build tests use sources

- CHANGELOG.md
- src/youwol/app/routers/backends/implementation.py
*  🥅 [custom-backends] Fallback to local-install if docker not available.
TG-2500 #closed
> TG-2500 Custom backend should fallback to local install if no docker

- CHANGELOG.md
- lib/yw_clients/yw_clients/common/headers.py
- src/youwol/app/routers/backends/__init__.py
- src/youwol/app/routers/backends/implementation.py
- src/youwol/app/routers/backends/router.py
- src/youwol/utils/clients/oidc/oidc_config.py
- src/youwol/utils/clients/oidc/tokens_manager.py
- src/youwol/utils/utils.py
*  📝 [custom-backends] Code documentation
*  🚨 [utils] Fix missing referenced DocStrings.
TG-2501 #closed
> TG-2501 Provide 'custom backends' code documentation

- CHANGELOG.md
- src/youwol/app/routers/backends/router.py
- src/youwol/app/routers/system/models.py
- src/youwol/app/routers/system/router.py
*  🚨 Add missing return type annotation
*  ✨ [app.routers.system] Add endpoint to open the host's file explorer
TG-2502 #closed
> TG-2502 Be able to open folder within host's files explorer

- CHANGELOG.md
- src/youwol/app/fastapi_app.py
*  ⬆️ [app] Upgrade `GET:/co-lab` target to `^0.6.0`
TG-2508 #closed
> TG-2508 Move to colab#^0.6.0

- CHANGELOG.md
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/dependencies_step.py
*  🐛 [pipeline-ts] Fix indirect deps. synchronization
TG-2375 #closed
> 🐛 [pipeline-ts] Fix indirect deps. synchronization

- doc/front-app/yarn.lock
- 📌 [doc/front-app] `http-proxy-middleware@2.0.7`
> TG-2536: fix GHSA-c7qv-q95q-8v27
