youwol/py-youwol

- youwol_tree_db_backend/configurations.py
- youwol_tree_db_backend/root_paths.py
The hard-coded limit to fetch folder's children has been increased to 1000. Should be enough for now for the rare cases for which we have more than 100 children.
A better implementation is required anyway, see issue [#158](https://tooling.dev.youwol.com/taiga/project/pyyouwol/t/158)
> TG-108 : more than 100 items in a folder

- youwol/environment/youwol_environment.py
This is a first step before making docdb documents in memory (see branch https://github.com/youwol/py-youwol/compare/main...feature/in-memory-db). The purpose is to keep backward compatibility with the cdn-client, http-clients & local-youwol-client tests.
second step is to use this new function in test configs
third step is to update the implementation of this function along with the branch feature/in-memory-docdb
> TG-423 : py-youwol & multithreading & indexed data files

- youwol/environment/youwol_environment.py
- youwol/pipelines/pipeline_typescript_weback_npm/common/utils.py
- youwol_utils/context.py
- youwol_utils/middlewares/root_middleware.py
- youwol_utils/utils_test.py
To be discussed, this is an example of how the test-utils functions can be used:
```
async def get_logs(session: PyYouwolSession, file: str, test: str):
http_port = session.configuration.system.httpPort
async with aiohttp.ClientSession() as session:
async with session.post(url=f"http://localhost:{http_port}/admin/custom-commands/get-logs",
json={"file": file, "testName": test}) as resp:
json_resp = await resp.json()
nodes = cast(List[Log], [NodeLogResponse(**node) for node in json_resp['nodes']])
leafs = cast(List[Log], [LeafLogResponse(**leaf) for leaf in json_resp['leafs']])
return list(sorted(nodes+leafs, key=lambda n: n.timestamp))
async def execute():
count = 100
consistency_testing = TestSession(
result_folder=Path(f'./test_stability_{datetime.now()}'),
publication=Publication( …
```
> TG-435 Unstable @youwol/local-youwol-client integrations tests

- youwol/pipelines/pipeline_typescript_weback_npm/regular/doc_step.py
- youwol/pipelines/pipeline_typescript_weback_npm/regular/webpack_dev_server_switch.py
The problem was when serving an app with webpack dev-server: some files are only available in CDN DB and not part of the scope of the dev. server.
Those files can now be configured within WebpackDevServerSwitch, in this case they are directly recovered from CDN DB.
> TG-360 apps-launcher: pb with @youwol/python-playground

- .github/workflows/pull_request_checks.yml
- src/youwol/app/environment/models/defaults.py
- src/youwol/app/environment/models/models_config.py
- src/youwol/app/environment/models/predefined_configs/py_youwol_tour/new_ts_app.py
- src/youwol/app/environment/models/predefined_configs/py_youwol_tour/new_ts_lib.py
- src/youwol/app/environment/online_environments.py
- 🐛 [environment] `get_standard_youwol_env` => fix hard coded
- ✨ [environment] default host => rely on `os.getenv("PY_YOUWOL_REMOTE")`  if any
- 🎨 [environment] System => improve name of the default env.
- ♻️ [environment/predefined configs] => CloudTarget.authentications explicit.
- 👷 Checks for PR into releases branches
TG-1727 #closed
> TG-1727 Py-youwol predefined configs can use 'int' environment

- src/youwol/backends/assets_gateway/deployment.py
- 🚚 tree-db: cluster service name is now tree-db
TG-1705
> TG-1705: Inconsistency naming for tree(-)db backend

- .github/workflows/pull_request_checks.yml
- src/youwol/backends/assets_gateway/routers/deprecated.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/npm_dependencies_version.py
- src/youwol/pipelines/pipeline_typescript_weback_npm/common/utils.py
- 🐛 `pipeline/ts`: existing dep spec from template
- 🐛 `assets-gw`: restore missing `await` keyword
- 📌 `pipeline/ts`: use shared configuration 1.1.0
- 💚 Use branches `feature/typescript-5.3.3`
TG-1911 #closed
TG-1949 #closed
> TG-1954: shared config. 1.1.0

- pyproject.toml
Tested by doing:
` rm -rf ./py-youwol && git clone -b feature/include-root__init__.py https://github.com/youwol/py-youwol.git && pipx uninstall youwol && pipx install ./py-youwol`
resulting site_packages of youwol does include `__init__.py` in addition to the expected modules.
running `youwol` and executing the request:
`http://localhost:2000/admin/system/documentation/youwol`
gives the expected response (including documentation from the root '__init__.py').
TG-1951 #closed
> TG-1951 py-youwol install & root `__init__.py`

- CHANGELOG.md
- src/youwol/utils/clients/oidc/tokens_manager.py
- 🐛 `tokens_manager` check typing only if not `None`
TG-2064 #closed
> TG-2064 error if Redis cache is empty

- pyproject.toml
- src/youwol/app/routers/custom_backends.py
- ⚰️ `custom_backends.py` unnecessary casting
TG-2028 #closed
> ⚰️ `custom_backends.py` unnecessary casting

- pyproject.toml
- src/youwol/app/routers/projects/models_project.py
- 🚨 `routers.prj.models_project` mute pylint E1102
TG-2030 #closed
> TG-2030 `routers.prj.models_project` mute pylint E1102

- CHANGELOG.md
- doc/src/app/py-doc/code.view.ts
- src/youwol/app/environment/__init__.py
- src/youwol/app/environment/config_from_module.py
- src/youwol/app/environment/models/flow_switches.py
- src/youwol/app/environment/models/model_remote.py
- src/youwol/app/environment/models/models_config.py
- src/youwol/app/environment/models/models_project.py
- src/youwol/app/routers/projects/models_project.py
*  ♻️ [py-doc] => `PyCodeView` uses `<code-snippet>` to improve snippets
*  📝 Docstrings uses `<code-snippet>` instead native MD syntax
TG-2147 #closed
> TG-2147 [doc] => improve code snippet display.

- CHANGELOG.md
- src/youwol/app/routers/local_cdn/router.py
- src/youwol/pipelines/publish_cdn.py
*  🚑️ [pipelines] => send CDN status update after publication in local DB.
TG-2175 #closed
> TG-2175 Missing CDN status event @ publish local

- CHANGELOG.md
- src/youwol/app/environment/models/tokens_storage/path_base.py
- src/youwol/app/fastapi_app.py
- src/youwol/app/routers/backends/implementation.py
- src/youwol/app/routers/environment/models.py
- src/youwol/app/routers/environment/router.py
- src/youwol/app/routers/system/router.py
- src/youwol/pipelines/pipeline_python_backend/pipeline.py
*  🎨 [env.models] => prettier persisted `TokensStoragePathBase`
*  ♻️ [app.routers.env] => clean `EnvironmentStatusResponse`
*  🐛 [fastapi_app] => JWT prov. `PyYouwol` before `CookieDynamicIssuer`
*  🥅 [app.routers.env] => `login` handle `NeedInteractiveSession`
TG-2183 #closed
> TG-2183 adapt 'login' end-point & EnvStatus API

- CHANGELOG.md
- src/youwol/app/routers/projects/models.py
- src/youwol/app/routers/projects/projects_loader.py
🐛 [app.routers.projects] => handle `FailurePipelineNotFound`
📝 [app.routers.projects] => add documentation
TG-2196 #closed
> TG-2196 projects failure due to pipelinesNotFound are not handled properly.

- CHANGELOG.md
- version_management.py
- 🐛 Correct `CHANGELOG.md` content & management
TG-2356 #closed
> TG-2356: Correct `CHANGELOG.md` management

- CHANGELOG.md
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/dependencies_step.py
*  🐛 [pipeline-ts] no cache for synced dependencies.
TG-2368 #closed
> TG-2368 Sync. dependencies: beware yarn's cache

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CHANGELOG.md
- 🔖 prepare for next version 0.1.13
- 💚 [release] allow installing local release in venv
- TG-2461: install local release in CI (#389)
- 💚 [release] push versions bump after publishing
- 🎨 Cleaning `.github/workflows/release.yml`
- TG-2462: push versions bump after publishing (#391)
- 👽️ [workflows] hidden files in uploaded config
- TG-2464: breaking change from `actions/upload-artefact` (#393)
- 💚 [release] Checkout with depth=3 for publishing
- TG-2467: [release] Checkout with depth=3 for publishing (#394)
- Merge branch 'main' into release/0.1.12
> TG-2452: merge branch `main` before merge back

- CHANGELOG.md
- src/youwol/utils/clients/oidc/oidc_config.py
- 🐛 [openid] remove trailing slash for discovery
- 🎨 Format `CHANGELOG.md`
TG-2489 #closed
> TG-2489: double slash when requesting OpenID config

- CHANGELOG.md
- src/youwol/pipelines/pipeline_python_backend/template/pyproject.toml.txt
- src/youwol/pipelines/pipeline_typescript_weback_npm/regular/pipeline.py
- src/youwol/pipelines/publish_cdn.py
*  ✨ [pipeline-TS] Allow `ignore` files in publication
*  🔧 [pipeline-py-backend] `pyproject.toml` finds submodules
TG-2532 #closed
TG-2533 #closed
> TG-2532 & TG-2533 : Allow ignore files in publication & pyproject.toml finds submodules

- CHANGELOG.md
- integrations/yw_config.py
- src/youwol/utils/utils_shell.py
*  🔊 [utils] `CommandException` reports its outputs
*  ✅ [IT] Add command `print-server-std-out`
TG-2525
> TG-2525 Pipeline backend: failed install should be displayed in std out
